name: MyCoreUIFramework

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "12.0"

############
# Packages
############

packages:
  SwiftyUtils:
    url: https://github.com/tbaranes/SwiftyUtils
    branch: master

############
# Targets
############

targets:

  # -----------
  # MyCoreUIFramework
  # -----------

  MyCoreUIFramework:
    type: framework
    platform: [iOS]

    # settings
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.myframework.MyCoreUIFramework"

    # scheme
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: MyCoreUIFrameworkTests_${platform}
          parallelizable: true
          randomExecutionOrder: true
        
    # sources
    sources:
      - Sources
      - path: Sources/Supporting Files/MyCoreUIFramework.h
        buildPhase: headers
        headerVisibility: public

    # dependencies
    dependencies:
      - package: SwiftyUtils

    # scripts
    postCompileScripts:
      # swiftlint
      - script: mint run swiftlint swiftlint --config .swiftlint.yml
        name: Swiftlint

  # -----------
  # MyCoreUIFrameworkTests
  # -----------

  MyCoreUIFrameworkTests:
    type: bundle.unit-test
    platform: [iOS]

    # sources
    sources:
      - Tests

    # dependencies
    dependencies:
      - target: MyCoreUIFramework_${platform}

    # scripts
    postCompileScripts:
      # swiftlint
      - script: mint run swiftlint swiftlint --config .swiftlint.yml
        name: Swiftlint
